################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Bsp \
Core/Src \
Core/Startup \
Drivers/STM32F7xx_HAL_Driver/Src \
fatfs/drivers \
fatfs/source \
freertos \
freertos/portable \
lwip-2.2.2/src/api \
lwip-2.2.2/src/apps/altcp_tls \
lwip-2.2.2/src/apps/http \
lwip-2.2.2/src/apps/lwiperf \
lwip-2.2.2/src/apps/mdns \
lwip-2.2.2/src/apps/mqtt \
lwip-2.2.2/src/apps/netbiosns \
lwip-2.2.2/src/apps/smtp \
lwip-2.2.2/src/apps/snmp \
lwip-2.2.2/src/apps/sntp \
lwip-2.2.2/src/apps/tftp \
lwip-2.2.2/src/core \
lwip-2.2.2/src/core/ipv4 \
lwip-2.2.2/src/core/ipv6 \
lwip-2.2.2/src/netif \
lwip-2.2.2/src/netif/ppp \
lwip-2.2.2/src/netif/ppp/polarssl \
lwip-2.2.2/system/os \
tinyusb/demo \
tinyusb/src/bsp \
tinyusb/src/class/audio \
tinyusb/src/class/bth \
tinyusb/src/class/cdc \
tinyusb/src/class/dfu \
tinyusb/src/class/hid \
tinyusb/src/class/midi \
tinyusb/src/class/msc \
tinyusb/src/class/net \
tinyusb/src/class/usbtmc \
tinyusb/src/class/vendor \
tinyusb/src/class/video \
tinyusb/src/common \
tinyusb/src/device \
tinyusb/src/host \
tinyusb/src/portable/analog/max3421 \
tinyusb/src/portable/bridgetek/ft9xx \
tinyusb/src/portable/chipidea/ci_fs \
tinyusb/src/portable/chipidea/ci_hs \
tinyusb/src/portable/dialog/da146xx \
tinyusb/src/portable/ehci \
tinyusb/src/portable/espressif/esp32sx \
tinyusb/src/portable/mentor/musb \
tinyusb/src/portable/microchip/pic \
tinyusb/src/portable/microchip/pic32mz \
tinyusb/src/portable/microchip/samd \
tinyusb/src/portable/microchip/samg \
tinyusb/src/portable/microchip/samx7x \
tinyusb/src/portable/mindmotion/mm32 \
tinyusb/src/portable/nordic/nrf5x \
tinyusb/src/portable/nuvoton/nuc120 \
tinyusb/src/portable/nuvoton/nuc121 \
tinyusb/src/portable/nuvoton/nuc505 \
tinyusb/src/portable/nxp/khci \
tinyusb/src/portable/nxp/lpc17_40 \
tinyusb/src/portable/nxp/lpc_ip3511 \
tinyusb/src/portable/ohci \
tinyusb/src/portable/raspberrypi/pio_usb \
tinyusb/src/portable/raspberrypi/rp2040 \
tinyusb/src/portable/renesas/rusb2 \
tinyusb/src/portable/sony/cxd56 \
tinyusb/src/portable/st/stm32_fsdev \
tinyusb/src/portable/st/typec \
tinyusb/src/portable/sunxi \
tinyusb/src/portable/synopsys/dwc2 \
tinyusb/src/portable/template \
tinyusb/src/portable/ti/msp430x5xx \
tinyusb/src/portable/valentyusb/eptri \
tinyusb/src/portable/wch \
tinyusb/src \
tinyusb/src/typec \

